/*
    You are given the customer visit log of a shop represented by a 0-indexed string customers consisting only of characters 'N' and 'Y':

    if the ith character is 'Y', it means that customers come at the ith hour
    whereas 'N' indicates that no customers come at the ith hour.
    If the shop closes at the jth hour (0 <= j <= n), the penalty is calculated as follows:

    For every hour when the shop is open and no customers come, the penalty increases by 1.
    For every hour when the shop is closed and customers come, the penalty increases by 1.
    Return the earliest hour at which the shop must be closed to incur a minimum penalty.

    Note that if a shop closes at the jth hour, it means the shop is closed at the hour j.

    

    Example 1:

    Input: customers = "YYNY"
    Output: 2
    Explanation: 
    - Closing the shop at the 0th hour incurs in 1+1+0+1 = 3 penalty.
    - Closing the shop at the 1st hour incurs in 0+1+0+1 = 2 penalty.
    - Closing the shop at the 2nd hour incurs in 0+0+0+1 = 1 penalty.
    - Closing the shop at the 3rd hour incurs in 0+0+1+1 = 2 penalty.
    - Closing the shop at the 4th hour incurs in 0+0+1+0 = 1 penalty.
    Closing the shop at 2nd or 4th hour gives a minimum penalty. Since 2 is earlier, the optimal closing time is 2.
    Example 2:

    Input: customers = "NNNNN"
    Output: 0
    Explanation: It is best to close the shop at the 0th hour as no customers arrive.
    Example 3:

    Input: customers = "YYYY"
    Output: 4
    Explanation: It is best to close the shop at the 4th hour as customers arrive at each hour.
    

    Constraints:

    1 <= customers.length <= 105
    customers consists only of characters 'Y' and 'N'.
 */
class ShopPenalty {
    public static void main(String[] args) {
        System.out.println(2 == bestClosingTime("YYNY"));
        System.out.println(4 == bestClosingTime("YNYY"));
        System.out.println(1 == bestClosingTime("YN"));
        System.out.println(0 == bestClosingTime("N"));
        System.out.println(4 == bestClosingTime("YYYY"));
        System.out.println(4 == bestClosingTime("YNYYN"));
        System.out.println(5 == bestClosingTime("NNYYYNNNNNNNNYYN"));
        System.out.println(8000 == bestClosingTime("NNYYNNNYYNYYNNNNYYNYYYYYYYNYYYYYYNYYNNNNNNNNYYNNYNNYYNYYYNYYYNYNNYYNYNYNNNNYYYYYYYNYNYYYNNNYNYNNYNNYYYYNYNNYYNNYYNYYNNYNNNNYYNYYYYYNYYYNYNNNNYYNYNYNNNNYNYYNNYYYYNYNYYYYYYNNNYYNNNNNNNYYNNYYYNYNYYNYNYYNYNNNNYNNNNYNNYNNYNYNYYYNYNNYYNYYYNYYNNNNYNYYNNNNNYNYYYYNNNNYYYYYNNNYNYNNNYYYYYNNYNYYNNNNNNNYYYYNNNNNYNNYYNNYYYNNYNYYNYNYYNYNYYYNNYYNYNYYNNNNNNYYYNYYNNNYNNYYYYNYYYNYNYNYYNNYNYNYNYNNNYYYNNYNYNYNNNNYNYYNYNNYYNNNNNYYYNNNYNYNNYNYNNNNYNYNYNYYYYYYNNYNNYYYNYYNNYYNYNYYNYNYYNYNNNNYNNYYNNNYYYYYNYYNYYYYNNNNYYYNYYNNYYNNYYYYYNYNNNNNYYYNYNYYNNNNNNNYNYNNYYNNNNYYNYYYYNNNNNNYNNNYYYNNYYNNYNYNNYNYNNNNYYNYNYYYNNYNYYNNYYNYNNNNYNNYNNNYYYNNYYYYYYNNNNNYYYNYYYNYYNYNNYNYYYNNYYYYYYYYNNNNYNYYYYYNYYNNYNYNNNYNNYYYNNYYNNNNYYNYNNNNNNYNYNNYYNYYYNNYYNNNYNNNYNNNYNNYYYNYNNYNYYNYYNYYYNNYYYYYYNYYYYYYNYNNNYYNYNNYNYYYNYYYYYNYNNYYYYNNYNYNNYNNNYYNYYNNNNNYNNYYNYYYNYYYYNYYNYYNYYYNYNYNNNYNNYYYYNYYNYNNNYYNNYYNNYYNNNYYNNYYNYYNYNNYYNNYNYYNYYYNNYNNNNNYNNYNNYYNNNYNNYNYYNNYNNNNNNNYYNYYNNNYNNYYYYNNNYNNYYYYNYYNYNYNYYNNNNNYNNYNYYYNNNYYNYYNNNYYYYYNYYNNNNNYNNYNNNYNNYNYNYNYNNNNYNYYYNNNNYNNNYYNNYYNNNYYNNYNYNNNNYNNYNYNYNYYNNYNYYNNYYNYYNYNNNYNYNYYNNNYNNYNNNNYYNYNNYYNYYYYNYNNYYYNNYNNYNYYYNYNNNYYNNNNYNYNYNNYYYYYYYYYNYYNYNYNYNNNNNYNNNNYYYNNNYNNYNNNNYYYYNNNYYNNYYYNYNYYNNYNYNNYYNNNYNYYYYNNNYNYYYYNNYYNYYNYYNNYYYNYNNYYYNNNYYYYYNNNYYNNYNNYNYNYNYNNYYYYNYNYNYYNYNNYYYYNYYNYYNYYYNYYNNYNNNNNYYNYNNYNNYYNNNYNNYNYNNYYYNYNNNYYNNYNYYYYYYYYNNYYYNNNNYNNNNYYNNNYNYNNNYYYYNYYYYYYYYNNYNNNNNNNNYNYYYYYYYYNNNNYYYYYNYNNNYNYNYYYNNYNNYYYYNNYYNNYNNYNYNNYYYNNYYYNYYNYNYYYYNYNYYYYNNYNYYNNYNYNNYNNYNYNYNNNNNNYNNNYNYNNNNNNYYNYYYYYYYNYNYNYNNYYNYNNNYYNNNYYNNNNYYNYYNNNYNNYNYNYNYYYNYYNYYNYYNNYNNYNYYNNNNNYYNNYNYYNYYNYYYNYNYYYNNNNNNYYYYNNNNYYYYNYYYNNNNYNYNYYNNYNNYNNNNYNYYYNNYNNNNYYYYYNYYYYNYYNYYYNYYYNYNNYYYNNNYYNNNNYYYNYNYNYNNNNYYNYYNYNNYNYNYYNYNYYNNNYYYNYYNNNNYNNYNYYYNNYNYNNNNYNNNYYYNNNYYNNYNNNYNNNYYYYNYNNNYYNNYYYNYYYNNYYNNYYNYNYNNNYYNNYYYYYNNNNYNYNYNYNNNYYYYNNNYNNNNYNYYNNNNNYYYNNYYNNYYYNNNNNYYNNYNNYNNYNYNNYNNNNNYNYNYYYYYNNYNNNYYYYNNYNNNNYYNYNYNNYYNNNNYNNNYNYNNYYNNNNYYNYYYYNYNNYYYYYNNNNNYYYYNYNYYNNNNNYYYYNYYYNYYNYNNYYNYNYYNNYNNYYNYNYNYNNNYYNNYNYYYNNNNYYYNNNYYYYYYNNNYNNNNYYYYYYNNNNNNNNYNYNYYNNYYNYYYYYNYNNNYYNYYYNYNNYNNNYYNNNYYNNNYYNYNNYNYNNNYYNNNNYNNNNNNNNYNYNNYNNYYNNYNYYNYNYYNYNYNYNNYNYNNYYNNYNNNNNNNNNNYNNYNYNYNYYNYYYNNYYYNYNYYYNNNNYNNNYNNNYNYYNNNYNNNNNNNNYYNNYNYNYNYYYNNNNYNNNYNNNNNYNYYYNYYYYNNYYNNNNYNNNNNNYNYNYNNNYNYYYYYYNNYYNYYYNNYNYNYNYYNNYNYYYYNYNYYYNNYYNYNYYNNNNNNNNNNYNNNYNYNYYYNNNYYYNNYYYYYNYYNYNYNYYYNYNNYYYYNNYNNNYNYNNYYNNYYNYYYNNNYNNNNYNNNYYYNYYYNNNNYNYYNYNNNNYYYNYNNNYNYNNYNNNYYYYNNYYYNNYYYYYYYNYYYNNNYNNYYYYNNNNNNYNYNNYYNYNNNNYNNNNNNNNYNYNYYNYYNYNYYYNNNNYYNYNNNYNNYYNNNNNYYNYYNNNYYNNYYYYNNYYNNYYYYYNYYYYYNYNNYYNNNNYNNYYYNYNNNYYNYNNNYYYYYYYNNNYYNNYYNNNYYNYYNYYYYNNYYYYNNNNNNYYYNNYNYNYNNNYNYNNNNNNYNYYNNYYNNNNNNNNYNYNNNNNYYNNNYNYYYNYNYNNNYYNNYNNYNNNYYNNNYNYYYYNNYYNNNNYNNYNYYNYYYNYNNNNYYNYYYYYNYNYYYNYNYNNYNNYYNNYYNNNYYYNNYNYNNYYYNNYNNNNNYYNYYNNNYYNYNYYYNNNYYNNNYNNYNYYYNYYNNYNNNYNNNYNNYNNYNYYNNYYYYYNYNNYYNYYYNYYNYYYYYYNNYYNNYYNNYNYYNYNNYNYNYNNNNYYYYYYNYYYNYNNYNNYNYNYYYYYYNNYNNNNNNNYYYYNNNNNYYNNNNYNYNYYNNNYNNNNNYNYNYYYYYNYYYNYNYYYNNNNNNYNYYNNNYNNNYNNYYNNYYYNNYYNYYNNNNNNNNYYYYYNNYYNNYYYNNNYYYYNNNNNNYYNYNYYNYYYYNYNYYYYYYYYNNNYNYYYNYNYNYNYYNNYYNYNNYNYYYYYNYNYNYYYNNYNYYNNYYNYYYYYYNNYYNNNNNYYYNNNYNYYYNNNYNYNYYNYYYNYNNYNYYYYNYYNNNNYYNYYYNNYYNNYNYYNYYNYYNYNNNNYYNYNNYNYYYYNYYYNNYYNYYYNYYYNYYYNYYYNNNNYYNNNYYYNNYYNYNNNNNYYNNNNYNYNYNYNNYYNNYNNYYYYYNYNYNNYNYNYNYNNYNNNYYYYYYNNYYYNNNYNYYYNYNYNNYNNYYYNNYYYNYYYYYNNYYNYNYNNNNYNYNYNYNYNNNYNNNNNYYNYNNYYNYNYNYYNNYNYNYYYYNYNNNYNYYYNYYNYYNYNYYYYYNYNNNNYYYYYNYNNYNYNYNYYNYNNYNYNNNNNNNYNYNNNNNNYYNNYNNNYYYYNYNYYYNYYNNNYNYYYNYYNNNYYNNNNNYNYYNYNNYNNYYYYNYYNNNNYNNNNYYYYNYYNYNYYYYNYYNNYNNYNNYYNYNNNNYYYNYYNNNYYNNNNNNNNYNYYYNYYYNNYYNNYYYNYNYNNNYYYYYYNYYNYNYYNNNNNNYNNNYNYNYNYYYNYYYNYNYYYYYYNNYYNYNNNNYNNYYNNYYNYYNYNNYYNYYYYYNNNYYNNNYYNYNNNNYYNNNYYYYNYNYNNNYYYYNNNYNNNYYNNYYYNNYYYYNNNYNNYNNYYNYYNNYNNNYYYYNYNYYNNNYNYYNYNYYYYYNNNYYYYNNYYNYNNNNYNNYYNNNNYNYNNYYNYNYNNNYYNYNYNNNNNNYNNNYNNYYYNNNYNYNYNYYNNYNYYNNNNYNNNYNNNNNYNNNYYYNNYYNNYNNNYNNYYYNYNYYNYYNNYYYNNYNYNYNNYYNYNYNNYYNYYYYNYNYYNNYYYNNNYYNNYNYNYNNYNNYNYYYNNYNYYNNYNNNYYYNNYYNYNYNYYNYYYNYYYNYYNNNNNNYYNYYYNNYYNNNYYNYNYYNYNYNNNNNNNYNNYNNYYNYNNYYNYNYNYNNNYNYYNYNYNNNNYNYYNNNNNYNNNNYYNNYYYNYNYYYNNYNYYYNYYNYNNNNYNNYYNNYYYYNNYNYNNYNYNNYNYNYYYYNNYNNYNYYYYNYNYNNNNYYYYYYYNNNNYNNNYNNNNYYYYYYNNYNNNYNYYNNYYNNNNNNNNYNNNNNYNNNYNYNNYNNYNYYNYNYYNYYYNYYNNNYNNYYNYYYNNYNNYNYYYYYNYNNNYNNNNNYNYNNYYYNNYYYNNYYNYYYYNYNYNYNYYYYYNNYNNYYYNNYYYNYYYYNYYNNNNYYNNNNNYNYYYNNNYNNYNNYNYNNNYYYYNNYNYYYNYYNNNNYNYYNNNNNYYYNYYYNNYYNNYNYNYNYNNYYNYNNNYNYNYNYNNYYYYNYYYYNYYNYYYNYYYNYYNYNYYNYYYYYYYYYYYYYYNYNNYNYNNYYNYNNNYNNYNNNNYYYYNYNNYYYNNYYYNNNYNNNNYYNYYYYNNNYNYYYYYYYYNNYYNNYNYNYNYNNNYYYNNYYYYNNYYYYNNYYNYYYNYNYNNNNNYYNYNNNNNNNYYNNYNNYNYYNNNNNNNYYYNNNYYNYYNNNYYNNNNNYYYYYYNNNNNNYYYYNNYNNNNYNYNNYYNYYNYYYYYYNNNNYYNYNYNYNNYNYNNYYNYNNYYNNYYNYYNYYYYYNNNYNNYNNNYNYYNNYNNYYNNYNYYYNNNNYYNYNYYNYNNNYNNYYYNYYNNNNYNYYNNYYYYYNNYYYYNYNYYYYNNNYNNNNNYNNYNNYNNNNNNYNYNNNNYNYNYNNYNYYYYYNYNNYYYYYYNYNYNYNNNYNYNNNYYNNNYNYNNNYNNNNYYNNNNNYNYNNYNNYNNNYNYYYNNYYYNNYYYNYNYYNYYYYYNYYNNNYYYNNNYYYNYYNYYNYNYNYNNNYNYNYYNYNYNYNNNNNYYYNYNYNNYYNYYNYYNNNYNYYYNYYNNYYYYNYYYNNNYNNNNYYNYNNNYYYNNYYYYNNNNYNNYYNNYYYYNYYNYYYNNYYNYNNYNYYYYYNYNNNYYNNYYYYYNNNNYYNYNYYNNNYNYYYNYNNNYNYNNNNYYYNYYNYYYNNYNNYNNYNNYYYYYYYNYNYYYYNYYYYNNYNNYYYYYYYYNYYYYYYNYYYNYYNYNYNNYYYNNNNYYYNNYYNNYYYYYNNYNNNNYNNYYNYYNYNNNYYYYNNYNNYNYYYYNYYYNNYNNYNYNNNNYYNNYYYNYNNYYYNNNYNNNYYNYYYNNYNNYYYYNYYNNYNYNYYYNYYYYYYYYYYYYNYYNNYYNNYYNYYYYNYYYNYNYNNYNNYNNNNYNYNNNNYYNNNYNYNYYYNYYYYNYNNNNYYYYNYYNYNNNNNYNYNYYNNNYYYYNYNYYNYYYNNNYNNYNNYYYYNNYNNYYNNNYNNNYYNYNNYYYYNNNNNYNYYYNNNNYNNYNYYYYYNYYYNNNYYYYNYNNNYYYYNYYNNNNNYYYNYYNNNYNNNYYYYNYYNNNNYYNYNNYNYNNYNNYNNYYNNYNYNYNNNNYNNYNYYNYNNNYYYNYNNYNYYNYYYYNYNNYYYNNNNYNYNNNYYNNYNYYNNYYNNNYYNNNYNNNNYNYNYNNNNYNYYNYYYNNYYYNYNYYYYYYNNYYYYYYNNYNYNYNYNNNNYYNYNYNNYYYNNYNNNYNYNNYYNNNYNYNYNYNYNYNNYYYYYNNNNYYNNNYYNYNYYYYYYYNNYNNYYNNNYYNYYYNYYNYNYNNYNNYNNYYYNYYYYYYYYNNYNYYYYNYYNNYYNNNNNYYNYNYYNNYYNYNNYNYNNYNNNYNNNNYYYNNYNNNYNNYYYNYNNNYNYYYYYYNYNYYYYYNYNNNNNYNYYYNYNNNNNNNNYYNNNNYNYYNNNNYYNNNYYNNYYNYYNNNYNYYYYNYYNNYYNYYNNYYNNNNYYNYYYYYYNYYNYNNYYNNNYNNNYYNNYNYYYNNNNNYYYYYYYYYYYYNNYYYYYYNNNYNYYYYYYYYNYYNYYYNYYNYNYNYNNNNNYYNYYNYNNNYYNNYNNYNYYNNYYNNNYYYYNYNNYYYNYYYNNNNNYYYYNYYNNYYYYNYYYNNYYNNNNYNYNNNYNNNNNYNNYNYYYYYNYYNYYNNYYNYNNNYNNNNNYNYYYYNNNNNYNYYYYYYYNYNYNNNYYYYYNNNYYYYNNNYYNYNNYNNYNYNNYNYNNYYYYYNYNYNYYNNYNYNYYNYNNNNYYNNYNYNYNYYYYNNYYYNNYNNNYNNYYYYNNNYYYNYYYYNNYNNNYNNYYNYNNYNYYNYYNYYYYNYYNYNNYNNNYYYNNYNYNYYYNNNYNNNYNYYNNYYNYNYYNYNYYYNYNYNNYNYYYYYYYYYNYNYNYNYYYYNNYNNNNYYNYYNYNYYYNYYNYNNNNNNNYNNYYYNYYYYYYYNNYNYYNNYYYYYNYNNNNNNNYYNYYNYYNNYNYYYYYYNYNYNNNNNYYYYYNYNYNNYNYYYYNNYYYYYNNNNYNYYYYYYYNNYYNYNNNYYYNNYNYYYYNNNNNYNYNYNYYYYNYYYYYNNNYYNNNYYYNNYNNYYNNYNYNYNYYYNNNYNNYNYNNYNNYNNYYYNYYYYNNNYYYYNNYYNNYYYNNNNNNNNNNNNNYYYYNYNYYNNNYNYNYYYNNNYNYNYYYYYYNYYYYYNYYYNNNYYYYYNNNYYYYYNYNNNNNYYNYYNYYYNYYYYYYYYYYYYYNYNNNNNNYNYYNYYNNNYYNNNNNYNNYYYYNNYYYNNNYNNNNNNNYYYNYYYYYNYNNYNNNNYYNYYNNYYNYNYYYNYNNYYYNNYYYYNYNYNNNNYYYNNYYNYNYNYNNNYNNYYNYNYNNNNNYYYYYYYYNYYNYYYYNNNNNYYYYYYNNNNYNNNYNNNYYYNYYNNNNNYNNNNYYYNYYYYYNNYYNYNYYYNNYNYNNNYNNYNYNYYNYNNYYNYNYNYNYYYNYYNYYYYYNNYYNYNYNNYYYNYNNNNYNNNNNNYYNNNYNNYYYNYNYYYNYNNYNYYYNNYYNNNYYNYNNYYYYYYNNNNNYYYNNNNNYNNYNYNNNNNNYNNYNNNYNYNNNYNNYYNYYNNNYNNYNNNNYYNYYYNYYNYYYYNNYYYYYYNYNNNYNNYYYNNNNNYNYNYYYYYNNYNYNNNYYYNYYNNYNYYNNYNYYNNNNNNYNYNYYNYNNNYNNYYNNNNYYYNNYNNNNNNYYYYYNNYYYYYNYNYNYNNNNNNYNNYYYYYNYYYYYNYNYNNNNYNYNYYNNYNNNYNYNNYYYYNNNYNYNYNNYYYNYNYNNYYNYNYYNYNNYNNNYNYNYYNNNYYNYYYYNYNYNNNYNNYNYNNYNNNYYYNYNNYNYNYYNYNYNYYYNNNNYYYNYYNYNYNNNYYYYYNNNYNNNNYYYYNYNNNYYYNYNYYNNNYNNNYNNNYYYNNNYYYYNYNYNNNYNNNYYNYYYYYYNNNNNNYNYYNNNNNNNYYNYNYYNYYYYYNYYYNYYYNYYYNNYNYNYYYNNYNNNYNYYNYYYYNYYNYNNYYNNNYNNNYNYNNYYYYNYNNNNYNYYNYYYNNYNNYYYNYNNNYYNYNYYYNYYYNNYNNNNYYYYYNNYNYNYNYNYNNYNYYNYYNYYYYNYYYYNYYYYNYYYYNNYNNNYYNYNNNNNYYNNYNYNNNNNNYNYYNNYNYNYYYYYNNYYYNYNNYNNNYNNYNYYYNNYNYYYYYNYYYYYYYNYNYYNYYNNYNYNNYYYYNYNNNYNYYNNYYYNYNNYYNYYYNYNNNNNYNYYNYNNNNYNYYNYNNYYNYNNYYYYYNYNNNNYNNYYNNYYYNNYNNYYYYNNNYNNYNNYYYYYNYYNYYNYYY"));
        System.out.println(0 == bestClosingTime("NNNYNN"));
    }

    public static int bestClosingTime(String customers) {

        boolean anyCustomers = customersCount(customers) > 0;
        int lastCustomers = customers.lastIndexOf('Y');

        if (!anyCustomers || lastCustomers == -1) {
            return 0;
        }

        return getOpenedHours(customers);
    }

    private static int getOpenedHours(String customers) {
        // last hours without customers doesnt have to be considered
        int lastCustomers = customers.lastIndexOf('Y');

        for (int hour = 0; hour < customers.length(); hour++) {
            boolean noCustomersLeft = lastCustomers + 1 == hour;
            if (noCustomersLeft) {
                return hour;
            }

            boolean isCustomerNextHour = customers.charAt(hour) == 'Y';
            boolean worthOpening = isWorthOpening(customers, hour);

            if (!worthOpening && !isCustomerNextHour) {
                return hour;
            }
        }
        return customers.length();
    }

    private static boolean isWorthOpening(String customers, int hour) {
        for (int i = 1 + hour; i < customers.length() + 1; i++) {
            String possibleOption = customers.substring(hour, i);
            double customersCount = customersCount(possibleOption);

            boolean worthOpening = customersCount > ((double) possibleOption.length() / 2);
            if (worthOpening){
                return true;
            }
        }
        return false;
    }

    private static int customersCount(String string) {
        return (int) string.chars().filter(ch -> ch == 'Y').count();
    }
}